// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TawtheefTest.Data.Structure;

public partial class Assignment
{
    public long Id { get; set; }

    public long ExamId { get; set; }

    public long CandidateId { get; set; }

    public string Status { get; set; }

    public string StartTime { get; set; }

    public string EndTime { get; set; }

    public string Score { get; set; }

    public long TotalPoints { get; set; }

    public long MaxPossiblePoints { get; set; }

    public long EasyQuestionsCorrect { get; set; }

    public long MediumQuestionsCorrect { get; set; }

    public long HardQuestionsCorrect { get; set; }

    public string CompletionDuration { get; set; }

    public long RankPosition { get; set; }

    public long TotalQuestions { get; set; }

    public long CompletedQuestions { get; set; }

    public long QuestionReplaced { get; set; }

    public string CreatedAt { get; set; }

    public string UpdatedAt { get; set; }

    public virtual Candidate Candidate { get; set; }

    public virtual ICollection<CandidateAnswer> CandidateAnswers { get; set; } = new List<CandidateAnswer>();

    public virtual Exam Exam { get; set; }
}