// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TawtheefTest.Data.Structure;

public partial class Assignment
{
    public int Id { get; set; }

    public int ExamId { get; set; }

    public int CandidateId { get; set; }

    public string Status { get; set; }

    public DateTime? StartTime { get; set; }

    public DateTime? EndTime { get; set; }

    public decimal? Score { get; set; }

    public int TotalPoints { get; set; }

    public int MaxPossiblePoints { get; set; }

    public int EasyQuestionsCorrect { get; set; }

    public int MediumQuestionsCorrect { get; set; }

    public int HardQuestionsCorrect { get; set; }

    public string CompletionDuration { get; set; }

    public int RankPosition { get; set; }

    public int TotalQuestions { get; set; }

    public int CompletedQuestions { get; set; }

    public bool QuestionReplaced { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual Candidate Candidate { get; set; }

    public virtual ICollection<CandidateAnswer> CandidateAnswers { get; set; } = new List<CandidateAnswer>();

    public virtual Exam Exam { get; set; }
}