// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TawtheefTest.Data.Structure;

public partial class CandidateAnswer
{
    public int Id { get; set; }

    public int AssignmentId { get; set; }

    public int QuestionId { get; set; }

    public string AnswerText { get; set; }

    public int? TrueFalseAnswer { get; set; }

    public int? SelectedOptionid { get; set; }

    public string SelectedOptionsJson { get; set; }

    public string MatchingPairsJson { get; set; }

    public string OrderingJson { get; set; }

    public bool IsCorrect { get; set; }

    public bool IsFlagged { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual Assignment Assignment { get; set; }

    public virtual Question Question { get; set; }
}