// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TawtheefTest.Data.Structure;

public partial class Candidate
{
    public long Id { get; set; }

    public string Name { get; set; }

    public long Phone { get; set; }

    public long JobId { get; set; }

    public long IsActive { get; set; }

    public string CreatedAt { get; set; }

    public string UpdatedAt { get; set; }

    public virtual ICollection<Assignment> Assignments { get; set; } = new List<Assignment>();

    public virtual Job Job { get; set; }

    public virtual ICollection<Notification> Notifications { get; set; } = new List<Notification>();
}