// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TawtheefTest.Data.Structure;

public partial class CandidateAnswer
{
    public long Id { get; set; }

    public long AssignmentId { get; set; }

    public string AnswerText { get; set; }

    public long? TrueFalseAnswer { get; set; }

    public long? SelectedOptionId { get; set; }

    public string SelectedOptionsJson { get; set; }

    public string MatchingPairsJson { get; set; }

    public string OrderingJson { get; set; }

    public long? IsCorrect { get; set; }

    public long IsFlagged { get; set; }

    public string CreatedAt { get; set; }

    public string UpdatedAt { get; set; }

    public long QuestionId { get; set; }

    public virtual Assignment Assignment { get; set; }

    public virtual Question Question { get; set; }
}