// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TawtheefTest.Data.Structure;

public partial class Candidate
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int Phone { get; set; }

    public int JobId { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<Assignment> Assignments { get; set; } = new List<Assignment>();

    public virtual Job Job { get; set; }

    public virtual ICollection<Notification> Notifications { get; set; } = new List<Notification>();
}