// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TawtheefTest.Data.Structure;

public partial class ExamQuestionSetManpping
{
    public long Id { get; set; }

    public long ExamId { get; set; }

    public long QuestionSetId { get; set; }

    public long DisplayOrder { get; set; }

    public virtual Exam Exam { get; set; }

    public virtual QuestionSet QuestionSet { get; set; }
}