// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TawtheefTest.Data.Structure;

public partial class Exam
{
    public long Id { get; set; }

    public long JobId { get; set; }

    public string Name { get; set; }

    public string Status { get; set; }

    public long Duration { get; set; }

    public long TotalQuestionsPerCandidate { get; set; }

    public string StartDate { get; set; }

    public string EndDate { get; set; }

    public long ShowResultsImmediately { get; set; }

    public long SendExamLinkToApplicants { get; set; }

    public string CreatedAt { get; set; }

    public string UpdatedAt { get; set; }

    public virtual ICollection<Assignment> Assignments { get; set; } = new List<Assignment>();

    public virtual ICollection<ExamQuestionSetManpping> ExamQuestionSetManppings { get; set; } = new List<ExamQuestionSetManpping>();

    public virtual Job Job { get; set; }
}