// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TawtheefTest.Data.Structure;

public partial class ExamQuestionSetMapping
{
    public int Id { get; set; }

    public int ExamId { get; set; }

    public int QuestionSetId { get; set; }

    public int DisplayOrder { get; set; }

    public virtual Exam Exam { get; set; }

    public virtual QuestionSet QuestionSet { get; set; }
}