// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TawtheefTest.Data.Structure;

public partial class MatchingPair
{
    public long Id { get; set; }

    public long QuestionId { get; set; }

    public string LeftItem { get; set; }

    public string RightItem { get; set; }

    public long DisplayOrder { get; set; }

    public long CorrectOrder { get; set; }

    public virtual Question Question { get; set; }
}