// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TawtheefTest.Data.Structure;

public partial class MatchingPair
{
    public int Id { get; set; }

    public int QuestionId { get; set; }

    public string LeftItem { get; set; }

    public string RightItem { get; set; }

    public int DisplayOrder { get; set; }

    public int CorrectOrder { get; set; }

    public virtual Question Question { get; set; }
}