// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TawtheefTest.Data.Structure;

public partial class Notification
{
    public long Id { get; set; }

    public long CandidateId { get; set; }

    public string Title { get; set; }

    public string Message { get; set; }

    public string Type { get; set; }

    public long IsRead { get; set; }

    public string CreatedAt { get; set; }

    public string ReadAt { get; set; }

    public virtual Candidate Candidate { get; set; }
}