// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TawtheefTest.Data.Structure;

public partial class Option
{
    public int Id { get; set; }

    public int QuestionId { get; set; }

    public string Text { get; set; }

    public int Index { get; set; }

    public bool IsCorrect { get; set; }

    public int Displayorder { get; set; }

    public virtual Question Question { get; set; }
}