// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TawtheefTest.Data.Structure;

public partial class OtpVerification
{
    public long Id { get; set; }

    public long PhoneNumber { get; set; }

    public string Otpcode { get; set; }

    public long IsVerified { get; set; }

    public string ExpiresAt { get; set; }

    public string CreatedAt { get; set; }
}