// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TawtheefTest.Data.Structure;

public partial class OtpVerification
{
    public int Id { get; set; }

    public int PhoneNumber { get; set; }

    public string OtpCode { get; set; }

    public bool IsVerified { get; set; }

    public DateTime ExpiresAt { get; set; }

    public DateTime CreatedAt { get; set; }
}