// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TawtheefTest.Data.Structure;

public partial class QuestionSet
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string QuestionType { get; set; }

    public string Language { get; set; }

    public string DifficultySet { get; set; }

    public int QuestionCount { get; set; }

    public int? OptionsCount { get; set; }

    public int? NumberOfRows { get; set; }

    public int? NumberOfCorrectOptions { get; set; }

    public string ContentSourceType { get; set; }

    public string Content { get; set; }

    public string FileName { get; set; }

    public string FileUploadedCode { get; set; }

    public string Url { get; set; }

    public string Status { get; set; }

    public string ErrorMessage { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? ProcessedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public int? RetryCount { get; set; }

    public string ResponseString { get; set; }

    public virtual ICollection<ExamQuestionSetMapping> ExamQuestionSetMappings { get; set; } = new List<ExamQuestionSetMapping>();

    public virtual ICollection<Question> Questions { get; set; } = new List<Question>();
}