// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TawtheefTest.Data.Structure;

public partial class Question
{
    public long Id { get; set; }

    public long QuestionSetId { get; set; }

    public long Index { get; set; }

    public string QuestionType { get; set; }

    public string QuestionText { get; set; }

    public string DifficultyLevel { get; set; }

    public long Points { get; set; }

    public long DisplayOrder { get; set; }

    public long? AnswerIndex { get; set; }

    public string Answer { get; set; }

    public long? TrueFalseAnswer { get; set; }

    public string InstructionText { get; set; }

    public string SampleAnswer { get; set; }

    public string ExternalId { get; set; }

    public string CreatedAt { get; set; }

    public virtual ICollection<CandidateAnswer> CandidateAnswers { get; set; } = new List<CandidateAnswer>();

    public virtual ICollection<MatchingPair> MatchingPairs { get; set; } = new List<MatchingPair>();

    public virtual ICollection<OptionChoice> OptionChoices { get; set; } = new List<OptionChoice>();

    public virtual ICollection<Option> Options { get; set; } = new List<Option>();

    public virtual ICollection<OrderingItem> OrderingItems { get; set; } = new List<OrderingItem>();

    public virtual QuestionSet QuestionSet { get; set; }
}