// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TawtheefTest.Data.Structure;

public partial class QuestionSet
{
    public long Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string QuestionType { get; set; }

    public string Language { get; set; }

    public string DifficultySet { get; set; }

    public long QuestionCount { get; set; }

    public long? OptionsCount { get; set; }

    public long? NumberOfRows { get; set; }

    public long? NumberOfCorrectOptions { get; set; }

    public string ContentSourceType { get; set; }

    public string Content { get; set; }

    public string FileName { get; set; }

    public string FileUploadedCode { get; set; }

    public string Url { get; set; }

    public string Status { get; set; }

    public string ErrorMessage { get; set; }

    public string CreatedAt { get; set; }

    public string ProcessedAt { get; set; }

    public string UpdatedAt { get; set; }

    public long? RetryCount { get; set; }

    public virtual ICollection<ExamQuestionSetManpping> ExamQuestionSetManppings { get; set; } = new List<ExamQuestionSetManpping>();

    public virtual ICollection<Question> Questions { get; set; } = new List<Question>();
}